# Generated by Django 5.2.6 on 2025-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='inputText',
            field=models.CharField(default='', max_length=500),
        ),
    ]
